language: cpp

compiler:
  - gcc

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - brew uninstall --force cmake
  - export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Coverage"

install:
  - brew install cmake
  - brew update
  - pip install cpp-coveralls

branches:
  except:
    - dev

before_script:
  - ls
  - export CXX=g++
  - export CC=gcc

script:
  - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ . && make && make test

after_success:
  - coveralls -i src --exclude lib --exclude tests --gcov-options '\-lp'
